context:
  name: "rundec"
  version: "0.5.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  # Windows can't seem to use git option
  # git: https://github.com/DavidMStraub/rundec-python.git
  # tag: ${{ version }}
  # Use exact commit as no tags for v0.5.1 or later (yet)
  # rev: "f22879245fc91dc25b6d2ba3c413dddf28fa8ad9"
  url: https://github.com/DavidMStraub/rundec-python/archive/f22879245fc91dc25b6d2ba3c413dddf28fa8ad9.tar.gz
  sha256: aec81fc7a88ebded71c1048cab27bbdeaf7d365612e275f46b21b2b5823e0814
  patches: add-pyproject-toml-for-build-system.patch

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - swig
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - rundec
      pip_check: true
  - requirements:
      run:
        - python
        - pip
    script:
      - pip list

about:
  homepage: https://github.com/DavidMStraub/rundec-python
  summary: 'Python wrapper around CRunDec'
  license: MIT
  license_file: LICENSE
  repository: https://github.com/DavidMStraub/rundec-python

extra:
  recipe-maintainers:
    - DavidMStraub
    - matthewfeickert
