context:
  name: "rundec"
  version: "0.5.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  # Windows can't seem to use git option
  if: win
  then:
    url: https://github.com/DavidMStraub/rundec-python/archive/db2ecffddcebc599a0e6394372353422f771922b.tar.gz
    sha256: fa038a5e7128060fa1068f7717a32a3cc7bc6a9fc8c0be5020b6ec2f31790447
  else:
    git: https://github.com/DavidMStraub/rundec-python.git
    # tag: ${{ version }}
    # sha256: fa038a5e7128060fa1068f7717a32a3cc7bc6a9fc8c0be5020b6ec2f31790447
    # Use exact commit as no tags for v0.5.1 or later (yet)
    rev: "db2ecffddcebc599a0e6394372353422f771922b"
  patches: add-pyproject-toml-for-build-system.patch

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - swig
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python

tests:
  - python:
      imports:
        - rundec
      pip_check: true
  - requirements:
      run:
        - python
        - pip
    script:
      - pip list

about:
  homepage: https://github.com/DavidMStraub/rundec-python
  summary: 'Python wrapper around CRunDec'
  license: GPL-3.0-or-later
  license_file: LICENSE
  repository: https://github.com/DavidMStraub/rundec-python

extra:
  recipe-maintainers:
    - DavidMStraub
    - matthewfeickert
